### PR TITLE
Update torch and use **kwargs for the DataLoader subclass

### PR DESCRIPTION
**Pull request by tmke8**
This should make it relatively future-proof.

### CODE REVIEW

**Comment by tmke8** [comment]
Okay, tests pass, which is good. But I guess the question is whether this also works with pytorch < 2.0?

**Comment by tmke8** [comment]
Looks like it won't work... https://github.com/pytorch/pytorch/blob/v1.13.1/torch/utils/data/dataloader.py#L240-L242

**Comment by tmke8** [comment]
Maybe we could use `kwargs` typing to solve this! That is, we don't mention `prefetch_factor` at all in the custom `__init__` and so something like:

```python
class DataLoaderKwargs(TypedDict):
    prefetch_factor: int

class CdtDataLoader(DataLoader):
    def __init__(self, [... all kinds of args...], **kwargs: Unpack[DataLoaderKwargs]):
        super().__init__([... all kinds of args...], **kwargs)
```

**Comment by tmke8** [comment]
AHH, I don't understand this error:

```
=========================== short test summary info ============================
FAILED tests/progress_test.py::test_cdt_progbar[ProgressBarTheme.QUATERION-TrainingMode.epoch] - TypeError: __init__ got unexpected keyword argument 'collate_fn'
FAILED tests/progress_test.py::test_cdt_progbar[ProgressBarTheme.QUATERION-TrainingMode.step] - TypeError: __init__ got unexpected keyword argument 'collate_fn'
FAILED tests/progress_test.py::test_cdt_progbar[ProgressBarTheme.CYBERPUNK-TrainingMode.epoch] - TypeError: __init__ got unexpected keyword argument 'collate_fn'
FAILED tests/progress_test.py::test_cdt_progbar[ProgressBarTheme.CYBERPUNK-TrainingMode.step] - TypeError: __init__ got unexpected keyword argument 'collate_fn'
FAILED tests/progress_test.py::test_cdt_progbar[ProgressBarTheme.GOOGLE-TrainingMode.epoch] - TypeError: __init__ got unexpected keyword argument 'collate_fn'
FAILED tests/progress_test.py::test_cdt_progbar[ProgressBarTheme.GOOGLE-TrainingMode.step] - TypeError: __init__ got unexpected keyword argument 'collate_fn'
```

The class didn't take a `collate_fn` argument before, so why is it a problem _now_?

**Comment by tmke8** [comment]
Wow, the madlads at pytorch_lightning actually inspect the signature of `__init__`: https://github.com/Lightning-AI/lightning/blob/9b69d512d97707124e2865883397f2a1fd859c2a/src/lightning/pytorch/utilities/data.py#L170 to determine which kwargs to pass. Did you know this, @MylesBartlett ?

**Review by MylesBartlett — APPROVED** [review]
